# Generated by Django 2.0.6 on 2018-06-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='img')),
                ('thumb', models.FilePathField(path='img/thumb')),
                ('instructions', models.CharField(max_length=5000)),
            ],
        ),
    ]
